spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: author-service-route
              uri: lb://author-service
              predicates:
                - Path=/api/v1/authors/**
            - id: book-service-static-route
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/books/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8889
