spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: book-service-route
              uri: lb://book-service
              predicates:
                - Path=/api/v1/books/**
            - id: user-service-route
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8888
