spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: author-service-route
              uri: lb://author-service
              predicates:
                - Path=/api/v1/authors/**
            - id: book-service-route
              uri: lb://book-service
              predicates:
                - Path=/api/v1/books/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8888
