spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
             # Book Service Yönlendirmesi
            - id: book-service
              uri: lb://BOOK-SERVICE
              predicates:
                - Path=/api/v1/books/**

            # Borrow Service Yönlendirmesi
            - id: borrow-service
              uri: lb://BORROW-SERVICE
              predicates:
                - Path=/api/v1/borrow/**

            # User Service Yönlendirmesi
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8888
