spring:
  application:
    name: bff-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8585/realms/turkcell-p1-dev
            user-name-attribute: preferred_username

        registration:
          keycloak:
            client-id: bff-service
            client-secret: 9LP2urGQyTyqlE9ORPrmV4LYkiBHU0Of
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/