eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8585/realms/turkcell-p1-realm
            user-name-attribute: preferred_username

        registration:
          keycloak:
            client-id: bff-service
            client-secret: xPToKd6xUDmX03PgRBPYAawy2ySENA03
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
