spring:
  application:
   name : config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eliffT/microservices-library-ms.git
          default-label: master
          search-paths:
            - configurations
            - configurations/{application}
          clone-on-start: true
          force-pull: true
          password: <token>
server:
  port: 8989